import { motion } from "framer-motion";
import Link from "next/link";
import Chip from '@material-ui/core/Chip';

export default function BlackBoxProject() {
  const easing = [0.6, -0.05, 0.01, 0.99];
  const fadeIn = {
    initial: {
      opacity: 0,
    },
    animate: {
      opacity: 1,
      transition: {
        duration: 1.5,
        ease: easing,
      },
    },
  };

  const tech = ["Java", "C++", "Shell", "Unix"];

  return (
    <motion.div exit="exit" initial="initial" animate="animate">
      <motion.div variants={fadeIn}>
        <hr className="mt-4" />
        <div>
          <div>
            <h6 className="middle-underline d-inline">The BlackBox Project</h6>
          </div>
          <p className="mt-2">
            The BlackBox is a cryptographic system that uses various techniques
            including trapdoor functions and deniable encryption algorithms to
            encrypt data while making it impossible for even a supercomputer or
            a quantum computer to crack the ciphers generated by it. The
            BlackBox is the successor to DHS One and is currently used to run
            Fringe Messenger.
          </p>
          {/* <h6 className="mt-4">Releases</h6> */}
          <div className="d-none">
            <Link passHref href={"https://blackbox.thedanielmark.com/"}>
              <a
                className="grey-to-white text-decoration-none"
                style={{ paddingLeft: "0px" }}
              >
                v1 (latest)
              </a>
            </Link>
          </div>
          <h6 className="mt-4">Technologies</h6>
          <div class="tech-badges">
            {tech.map((chip) => {
              return (
                <Chip size="small" key={chip} label={chip} />
              );
            })}
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
}